version: '3'
services:
  client:
    image: yhchan0918/nba-client:1.2
    container_name: client-dc
    ports:
      - 8501:8501
    depends_on:
      - server
    volumes:
      - './client:/app'
  server:
    image: yhchan0918/nba-server:1.0
    container_name: server-dc
    ports:
      - 8000:8000
    volumes:
      - './server:/app'
