version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client-dc
    ports:
      - 8501:8501
    depends_on:
      - server
    volumes:
      - './client:/app'
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-dc
    ports:
      - 8000:8000
    volumes:
      - './server:/app'
